services:
  - type: web
    name: seci-web
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --config gunicorn_conf.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: seci-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: seci-kv
          type: keyvalue
          property: connectionString
      - key: SITE_URL
        value: https://YOUR-SERVICE.onrender.com

  - type: keyvalue
    name: seci-kv
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: seci-db
    plan: free
    postgresMajorVersion: "15"
