databases:
  - name: seci-db
    plan: free
    postgresMajorVersion: 15

services:
  - type: keyvalue
    name: seci-kv
    plan: free

  - type: web
    name: seci-web
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: bash -lc 'python -m app.init_db && gunicorn -c gunicorn_conf.py "app:create_app()" --access-logfile - --error-logfile - --log-level debug'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seci-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: seci-kv
          type: keyvalue
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SITE_URL
        value: https://seci-p6co.onrender.com
      - key: FLASK_DEBUG
        value: "0"
